//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// IntentsForwarder
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const intentsForwarderAbi = [
  {
    type: 'constructor',
    inputs: [
      { name: '_usdt', internalType: 'address', type: 'address' },
      { name: '_usdc', internalType: 'address', type: 'address' },
      { name: '_owner', internalType: 'address', type: 'address' },
    ],
    stateMutability: 'nonpayable',
  },
  { type: 'receive', stateMutability: 'payable' },
  {
    type: 'function',
    inputs: [],
    name: 'RECEIVER_BYTECODE_HASH',
    outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'RECEIVER_IMPLEMENTATION',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'SWAP_EXECUTOR',
    outputs: [
      { name: '', internalType: 'contract SwapExecutor', type: 'address' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'USDC',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'USDT',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'eventChainTip',
    outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'eventSeq',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'salt', internalType: 'bytes32', type: 'bytes32' }],
    name: 'getReceiver',
    outputs: [
      {
        name: 'receiver',
        internalType: 'contract UntronReceiver',
        type: 'address',
      },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'owner',
    outputs: [{ name: 'result', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'salt', internalType: 'bytes32', type: 'bytes32' }],
    name: 'predictReceiverAddress',
    outputs: [
      { name: 'predicted', internalType: 'address payable', type: 'address' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      {
        name: 'req',
        internalType: 'struct IntentsForwarder.PullRequest',
        type: 'tuple',
        components: [
          { name: 'targetChain', internalType: 'uint256', type: 'uint256' },
          {
            name: 'beneficiary',
            internalType: 'address payable',
            type: 'address',
          },
          { name: 'beneficiaryClaimOnly', internalType: 'bool', type: 'bool' },
          { name: 'intentHash', internalType: 'bytes32', type: 'bytes32' },
          { name: 'forwardSalt', internalType: 'bytes32', type: 'bytes32' },
          { name: 'balance', internalType: 'uint256', type: 'uint256' },
          { name: 'tokenIn', internalType: 'address', type: 'address' },
          { name: 'tokenOut', internalType: 'address', type: 'address' },
          {
            name: 'swapData',
            internalType: 'struct Call[]',
            type: 'tuple[]',
            components: [
              { name: 'to', internalType: 'address', type: 'address' },
              { name: 'value', internalType: 'uint256', type: 'uint256' },
              { name: 'data', internalType: 'bytes', type: 'bytes' },
            ],
          },
          { name: 'bridgeData', internalType: 'bytes', type: 'bytes' },
        ],
      },
    ],
    name: 'pullFromReceiver',
    outputs: [{ name: 'amountOut', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'address', type: 'address' }],
    name: 'quoterByToken',
    outputs: [{ name: '', internalType: 'contract IQuoter', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    inputs: [
      {
        name: '_usdtBridger',
        internalType: 'contract IBridger',
        type: 'address',
      },
      {
        name: '_usdcBridger',
        internalType: 'contract IBridger',
        type: 'address',
      },
    ],
    name: 'setBridgers',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'targetToken', internalType: 'address', type: 'address' },
      { name: 'quoter', internalType: 'contract IQuoter', type: 'address' },
    ],
    name: 'setQuoter',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'newOwner', internalType: 'address', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'usdcBridger',
    outputs: [{ name: '', internalType: 'contract IBridger', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'usdtBridger',
    outputs: [{ name: '', internalType: 'contract IBridger', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'forwardId',
        internalType: 'bytes32',
        type: 'bytes32',
        indexed: true,
      },
      {
        name: 'bridger',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'tokenOut',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'amountIn',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'targetChain',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'BridgeInitiated',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'usdtBridger',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'usdcBridger',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
    ],
    name: 'BridgersSet',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'eventSeq',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'prevTip',
        internalType: 'bytes32',
        type: 'bytes32',
        indexed: true,
      },
      {
        name: 'newTip',
        internalType: 'bytes32',
        type: 'bytes32',
        indexed: true,
      },
      {
        name: 'eventSignature',
        internalType: 'bytes32',
        type: 'bytes32',
        indexed: false,
      },
      {
        name: 'abiEncodedEventData',
        internalType: 'bytes',
        type: 'bytes',
        indexed: false,
      },
    ],
    name: 'EventAppended',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'forwardId',
        internalType: 'bytes32',
        type: 'bytes32',
        indexed: true,
      },
      { name: 'ephemeral', internalType: 'bool', type: 'bool', indexed: false },
      {
        name: 'amountPulled',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'amountForwarded',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'relayerRebate',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'msgValueRefunded',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'settledLocally',
        internalType: 'bool',
        type: 'bool',
        indexed: false,
      },
      {
        name: 'bridger',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
      {
        name: 'expectedBridgeOut',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'bridgeDataHash',
        internalType: 'bytes32',
        type: 'bytes32',
        indexed: false,
      },
    ],
    name: 'ForwardCompleted',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'forwardId',
        internalType: 'bytes32',
        type: 'bytes32',
        indexed: true,
      },
      {
        name: 'baseReceiverSalt',
        internalType: 'bytes32',
        type: 'bytes32',
        indexed: true,
      },
      {
        name: 'forwardSalt',
        internalType: 'bytes32',
        type: 'bytes32',
        indexed: true,
      },
      {
        name: 'intentHash',
        internalType: 'bytes32',
        type: 'bytes32',
        indexed: false,
      },
      {
        name: 'targetChain',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'beneficiary',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
      {
        name: 'beneficiaryClaimOnly',
        internalType: 'bool',
        type: 'bool',
        indexed: false,
      },
      {
        name: 'balanceParam',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'tokenIn',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
      {
        name: 'tokenOut',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
      {
        name: 'receiverUsed',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
      {
        name: 'ephemeralReceiver',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
    ],
    name: 'ForwardStarted',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'oldOwner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'newOwner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
    ],
    name: 'OwnershipTransferred',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'tokenIn',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'quoter',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
    ],
    name: 'QuoterSet',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'receiverSalt',
        internalType: 'bytes32',
        type: 'bytes32',
        indexed: true,
      },
      {
        name: 'receiver',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'implementation',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
    ],
    name: 'ReceiverDeployed',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'forwardId',
        internalType: 'bytes32',
        type: 'bytes32',
        indexed: true,
      },
      {
        name: 'tokenIn',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'tokenOut',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'minOut',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'actualOut',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'SwapExecuted',
  },
  { type: 'error', inputs: [], name: 'AlreadyInitialized' },
  { type: 'error', inputs: [], name: 'InsufficientOutputAmount' },
  { type: 'error', inputs: [], name: 'NewOwnerIsZeroAddress' },
  { type: 'error', inputs: [], name: 'PullerUnauthorized' },
  { type: 'error', inputs: [], name: 'SwapOnEphemeralReceiversNotAllowed' },
  { type: 'error', inputs: [], name: 'Unauthorized' },
  { type: 'error', inputs: [], name: 'UnsupportedOutputToken' },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// StatefulTronTxReader
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const statefulTronTxReaderAbi = [
  {
    type: 'constructor',
    inputs: [
      { name: '_srs', internalType: 'bytes20[27]', type: 'bytes20[27]' },
      {
        name: '_witnessDelegatees',
        internalType: 'bytes20[27]',
        type: 'bytes20[27]',
      },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'blocks', internalType: 'bytes[20]', type: 'bytes[20]' },
      { name: 'encodedTx', internalType: 'bytes', type: 'bytes' },
      { name: 'proof', internalType: 'bytes32[]', type: 'bytes32[]' },
      { name: 'index', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'readDelegateResourceContract',
    outputs: [
      {
        name: 'delegation',
        internalType: 'struct DelegateResourceContract',
        type: 'tuple',
        components: [
          { name: 'txId', internalType: 'bytes32', type: 'bytes32' },
          { name: 'tronBlockNumber', internalType: 'uint256', type: 'uint256' },
          { name: 'balanceSun', internalType: 'uint256', type: 'uint256' },
          { name: 'lockPeriod', internalType: 'uint256', type: 'uint256' },
          { name: 'ownerTron', internalType: 'bytes21', type: 'bytes21' },
          { name: 'receiverTron', internalType: 'bytes21', type: 'bytes21' },
          {
            name: 'tronBlockTimestamp',
            internalType: 'uint32',
            type: 'uint32',
          },
          { name: 'resource', internalType: 'uint8', type: 'uint8' },
          { name: 'lock', internalType: 'bool', type: 'bool' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'blocks', internalType: 'bytes[20]', type: 'bytes[20]' },
      { name: 'encodedTx', internalType: 'bytes', type: 'bytes' },
      { name: 'proof', internalType: 'bytes32[]', type: 'bytes32[]' },
      { name: 'index', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'readTransferContract',
    outputs: [
      {
        name: 'transfer',
        internalType: 'struct TransferContract',
        type: 'tuple',
        components: [
          { name: 'txId', internalType: 'bytes32', type: 'bytes32' },
          { name: 'tronBlockNumber', internalType: 'uint256', type: 'uint256' },
          {
            name: 'tronBlockTimestamp',
            internalType: 'uint32',
            type: 'uint32',
          },
          { name: 'senderTron', internalType: 'bytes21', type: 'bytes21' },
          { name: 'toTron', internalType: 'bytes21', type: 'bytes21' },
          { name: 'amountSun', internalType: 'uint256', type: 'uint256' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'blocks', internalType: 'bytes[20]', type: 'bytes[20]' },
      { name: 'encodedTx', internalType: 'bytes', type: 'bytes' },
      { name: 'proof', internalType: 'bytes32[]', type: 'bytes32[]' },
      { name: 'index', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'readTriggerSmartContract',
    outputs: [
      {
        name: 'callData',
        internalType: 'struct TriggerSmartContract',
        type: 'tuple',
        components: [
          { name: 'txId', internalType: 'bytes32', type: 'bytes32' },
          { name: 'tronBlockNumber', internalType: 'uint256', type: 'uint256' },
          {
            name: 'tronBlockTimestamp',
            internalType: 'uint32',
            type: 'uint32',
          },
          { name: 'senderTron', internalType: 'bytes21', type: 'bytes21' },
          { name: 'toTron', internalType: 'bytes21', type: 'bytes21' },
          { name: 'callValueSun', internalType: 'uint256', type: 'uint256' },
          { name: 'data', internalType: 'bytes', type: 'bytes' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'bytes20', type: 'bytes20' }],
    name: 'srIndexPlus1',
    outputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    name: 'srs',
    outputs: [{ name: '', internalType: 'bytes20', type: 'bytes20' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    name: 'witnessDelegatees',
    outputs: [{ name: '', internalType: 'bytes20', type: 'bytes20' }],
    stateMutability: 'view',
  },
  {
    type: 'error',
    inputs: [{ name: 'sr', internalType: 'bytes20', type: 'bytes20' }],
    name: 'DuplicateSr',
  },
  { type: 'error', inputs: [], name: 'InvalidBlockSequence' },
  {
    type: 'error',
    inputs: [{ name: 'got', internalType: 'uint256', type: 'uint256' }],
    name: 'InvalidEncodedBlockLength',
  },
  { type: 'error', inputs: [], name: 'InvalidHeaderPrefix' },
  { type: 'error', inputs: [], name: 'InvalidTxMerkleProof' },
  {
    type: 'error',
    inputs: [{ name: 'got', internalType: 'uint8', type: 'uint8' }],
    name: 'InvalidWitnessAddressPrefix',
  },
  { type: 'error', inputs: [], name: 'InvalidWitnessSignature' },
  { type: 'error', inputs: [], name: 'NotDelegateResourceContract' },
  { type: 'error', inputs: [], name: 'NotTransferContract' },
  { type: 'error', inputs: [], name: 'NotTriggerSmartContract' },
  { type: 'error', inputs: [], name: 'ProtoInvalidWireType' },
  { type: 'error', inputs: [], name: 'ProtoTruncated' },
  {
    type: 'error',
    inputs: [
      { name: 'index', internalType: 'uint256', type: 'uint256' },
      { name: 'prev', internalType: 'bytes20', type: 'bytes20' },
      { name: 'next', internalType: 'bytes20', type: 'bytes20' },
    ],
    name: 'SrSetNotSorted',
  },
  { type: 'error', inputs: [], name: 'TimestampOverflow' },
  { type: 'error', inputs: [], name: 'TronInvalidBalance' },
  { type: 'error', inputs: [], name: 'TronInvalidCallValue' },
  { type: 'error', inputs: [], name: 'TronInvalidContractLength' },
  { type: 'error', inputs: [], name: 'TronInvalidContractPrefix' },
  { type: 'error', inputs: [], name: 'TronInvalidLock' },
  { type: 'error', inputs: [], name: 'TronInvalidLockPeriod' },
  { type: 'error', inputs: [], name: 'TronInvalidOwnerLength' },
  { type: 'error', inputs: [], name: 'TronInvalidOwnerPrefix' },
  { type: 'error', inputs: [], name: 'TronInvalidReceiverLength' },
  { type: 'error', inputs: [], name: 'TronInvalidReceiverPrefix' },
  { type: 'error', inputs: [], name: 'TronInvalidResource' },
  { type: 'error', inputs: [], name: 'TronTxNotSuccessful' },
  {
    type: 'error',
    inputs: [{ name: 'sr', internalType: 'bytes20', type: 'bytes20' }],
    name: 'UnknownSr',
  },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// SwapExecutor
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const swapExecutorAbi = [
  { type: 'constructor', inputs: [], stateMutability: 'nonpayable' },
  { type: 'receive', stateMutability: 'payable' },
  {
    type: 'function',
    inputs: [],
    name: 'OWNER',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      {
        name: 'calls',
        internalType: 'struct Call[]',
        type: 'tuple[]',
        components: [
          { name: 'to', internalType: 'address', type: 'address' },
          { name: 'value', internalType: 'uint256', type: 'uint256' },
          { name: 'data', internalType: 'bytes', type: 'bytes' },
        ],
      },
      { name: 'token', internalType: 'address', type: 'address' },
      { name: 'expectedAmount', internalType: 'uint256', type: 'uint256' },
      { name: 'recipient', internalType: 'address payable', type: 'address' },
    ],
    name: 'execute',
    outputs: [{ name: 'actualOut', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'error',
    inputs: [{ name: 'callIndex', internalType: 'uint256', type: 'uint256' }],
    name: 'CallFailed',
  },
  { type: 'error', inputs: [], name: 'InsufficientOutput' },
  { type: 'error', inputs: [], name: 'NotOwner' },
  { type: 'error', inputs: [], name: 'Reentrancy' },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// TronTxReaderErrors
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const tronTxReaderErrorsAbi = [
  {
    type: 'error',
    inputs: [{ name: 'sr', internalType: 'bytes20', type: 'bytes20' }],
    name: 'DuplicateSr',
  },
  { type: 'error', inputs: [], name: 'InvalidBlockSequence' },
  {
    type: 'error',
    inputs: [{ name: 'got', internalType: 'uint256', type: 'uint256' }],
    name: 'InvalidEncodedBlockLength',
  },
  { type: 'error', inputs: [], name: 'InvalidHeaderPrefix' },
  { type: 'error', inputs: [], name: 'InvalidTxMerkleProof' },
  {
    type: 'error',
    inputs: [{ name: 'got', internalType: 'uint8', type: 'uint8' }],
    name: 'InvalidWitnessAddressPrefix',
  },
  { type: 'error', inputs: [], name: 'InvalidWitnessSignature' },
  { type: 'error', inputs: [], name: 'NotDelegateResourceContract' },
  { type: 'error', inputs: [], name: 'NotTransferContract' },
  { type: 'error', inputs: [], name: 'NotTriggerSmartContract' },
  {
    type: 'error',
    inputs: [
      { name: 'index', internalType: 'uint256', type: 'uint256' },
      { name: 'prev', internalType: 'bytes20', type: 'bytes20' },
      { name: 'next', internalType: 'bytes20', type: 'bytes20' },
    ],
    name: 'SrSetNotSorted',
  },
  { type: 'error', inputs: [], name: 'TimestampOverflow' },
  { type: 'error', inputs: [], name: 'TronInvalidBalance' },
  { type: 'error', inputs: [], name: 'TronInvalidCallValue' },
  { type: 'error', inputs: [], name: 'TronInvalidContractLength' },
  { type: 'error', inputs: [], name: 'TronInvalidContractPrefix' },
  { type: 'error', inputs: [], name: 'TronInvalidLock' },
  { type: 'error', inputs: [], name: 'TronInvalidLockPeriod' },
  { type: 'error', inputs: [], name: 'TronInvalidOwnerLength' },
  { type: 'error', inputs: [], name: 'TronInvalidOwnerPrefix' },
  { type: 'error', inputs: [], name: 'TronInvalidReceiverLength' },
  { type: 'error', inputs: [], name: 'TronInvalidReceiverPrefix' },
  { type: 'error', inputs: [], name: 'TronInvalidResource' },
  { type: 'error', inputs: [], name: 'TronTxNotSuccessful' },
  {
    type: 'error',
    inputs: [{ name: 'sr', internalType: 'bytes20', type: 'bytes20' }],
    name: 'UnknownSr',
  },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// UntronIntents
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const untronIntentsAbi = [
  {
    type: 'constructor',
    inputs: [
      { name: '_owner', internalType: 'address', type: 'address' },
      { name: 'v3', internalType: 'contract IUntronV3', type: 'address' },
      { name: 'usdt', internalType: 'address', type: 'address' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'INTENT_CLAIM_DEPOSIT',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'RECEIVER_INTENT_DURATION',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'TIME_TO_FILL',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'USDT',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'V3',
    outputs: [
      { name: '', internalType: 'contract IUntronV3', type: 'address' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'id', internalType: 'bytes32', type: 'bytes32' }],
    name: 'claimIntent',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      {
        name: 'forwarder',
        internalType: 'contract IntentsForwarder',
        type: 'address',
      },
      { name: 'toTron', internalType: 'address', type: 'address' },
      { name: 'forwardSalt', internalType: 'bytes32', type: 'bytes32' },
      { name: 'token', internalType: 'address', type: 'address' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'claimVirtualReceiverIntent',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'id', internalType: 'bytes32', type: 'bytes32' }],
    name: 'closeIntent',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      {
        name: 'intent',
        internalType: 'struct UntronIntents.Intent',
        type: 'tuple',
        components: [
          {
            name: 'intentType',
            internalType: 'enum UntronIntents.IntentType',
            type: 'uint8',
          },
          { name: 'intentSpecs', internalType: 'bytes', type: 'bytes' },
          {
            name: 'refundBeneficiary',
            internalType: 'address',
            type: 'address',
          },
          { name: 'token', internalType: 'address', type: 'address' },
          { name: 'amount', internalType: 'uint256', type: 'uint256' },
        ],
      },
      { name: 'deadline', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'createIntent',
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    inputs: [
      {
        name: 'forwarder',
        internalType: 'contract IntentsForwarder',
        type: 'address',
      },
      { name: 'toTron', internalType: 'address', type: 'address' },
      { name: 'forwardSalt', internalType: 'bytes32', type: 'bytes32' },
      { name: 'token', internalType: 'address', type: 'address' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'createIntentFromReceiver',
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'eventChainTip',
    outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'eventSeq',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      {
        name: 'forwarder',
        internalType: 'contract IntentsForwarder',
        type: 'address',
      },
      { name: 'toTron', internalType: 'address', type: 'address' },
      { name: 'forwardSalt', internalType: 'bytes32', type: 'bytes32' },
      { name: 'token', internalType: 'address', type: 'address' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'fundReceiverIntent',
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
    name: 'intents',
    outputs: [
      {
        name: 'intent',
        internalType: 'struct UntronIntents.Intent',
        type: 'tuple',
        components: [
          {
            name: 'intentType',
            internalType: 'enum UntronIntents.IntentType',
            type: 'uint8',
          },
          { name: 'intentSpecs', internalType: 'bytes', type: 'bytes' },
          {
            name: 'refundBeneficiary',
            internalType: 'address',
            type: 'address',
          },
          { name: 'token', internalType: 'address', type: 'address' },
          { name: 'amount', internalType: 'uint256', type: 'uint256' },
        ],
      },
      { name: 'solverClaimedAt', internalType: 'uint256', type: 'uint256' },
      { name: 'deadline', internalType: 'uint256', type: 'uint256' },
      { name: 'solver', internalType: 'address', type: 'address' },
      { name: 'solved', internalType: 'bool', type: 'bool' },
      { name: 'funded', internalType: 'bool', type: 'bool' },
      { name: 'settled', internalType: 'bool', type: 'bool' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'owner',
    outputs: [{ name: 'result', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'id', internalType: 'bytes32', type: 'bytes32' },
      { name: 'blocks', internalType: 'bytes[20]', type: 'bytes[20]' },
      { name: 'encodedTx', internalType: 'bytes', type: 'bytes' },
      { name: 'proof', internalType: 'bytes32[]', type: 'bytes32[]' },
      { name: 'index', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'proveIntentFill',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      {
        name: 'forwarder',
        internalType: 'contract IntentsForwarder',
        type: 'address',
      },
      { name: 'toTron', internalType: 'address', type: 'address' },
      { name: 'forwardSalt', internalType: 'bytes32', type: 'bytes32' },
      { name: 'token', internalType: 'address', type: 'address' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'receiverIntentId',
    outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    inputs: [{ name: 'amount', internalType: 'uint256', type: 'uint256' }],
    name: 'recommendedIntentFee',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'recommendedIntentFeeFlat',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'recommendedIntentFeePpm',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'ppm', internalType: 'uint256', type: 'uint256' },
      { name: 'flat', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'setRecommendedIntentFee',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'id', internalType: 'bytes32', type: 'bytes32' }],
    name: 'settleIntent',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'newOwner', internalType: 'address', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    inputs: [{ name: 'id', internalType: 'bytes32', type: 'bytes32' }],
    name: 'unclaimIntent',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'eventSeq',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {
        name: 'prevTip',
        internalType: 'bytes32',
        type: 'bytes32',
        indexed: true,
      },
      {
        name: 'newTip',
        internalType: 'bytes32',
        type: 'bytes32',
        indexed: true,
      },
      {
        name: 'eventSignature',
        internalType: 'bytes32',
        type: 'bytes32',
        indexed: false,
      },
      {
        name: 'abiEncodedEventData',
        internalType: 'bytes',
        type: 'bytes',
        indexed: false,
      },
    ],
    name: 'EventAppended',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'id', internalType: 'bytes32', type: 'bytes32', indexed: true },
      {
        name: 'solver',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'depositAmount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'IntentClaimed',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'id', internalType: 'bytes32', type: 'bytes32', indexed: true },
      {
        name: 'caller',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      { name: 'solved', internalType: 'bool', type: 'bool', indexed: false },
      { name: 'funded', internalType: 'bool', type: 'bool', indexed: false },
      { name: 'settled', internalType: 'bool', type: 'bool', indexed: false },
      {
        name: 'refundBeneficiary',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
      {
        name: 'escrowToken',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
      {
        name: 'escrowRefunded',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'depositToken',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
      {
        name: 'depositToCaller',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'depositToRefundBeneficiary',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'depositToSolver',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'IntentClosed',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'id', internalType: 'bytes32', type: 'bytes32', indexed: true },
      {
        name: 'creator',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'intentType',
        internalType: 'uint8',
        type: 'uint8',
        indexed: false,
      },
      {
        name: 'token',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
      {
        name: 'amount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'refundBeneficiary',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
      {
        name: 'deadline',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'intentSpecs',
        internalType: 'bytes',
        type: 'bytes',
        indexed: false,
      },
    ],
    name: 'IntentCreated',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'id', internalType: 'bytes32', type: 'bytes32', indexed: true },
      {
        name: 'funder',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'token',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
      {
        name: 'amount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'IntentFunded',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'id', internalType: 'bytes32', type: 'bytes32', indexed: true },
      {
        name: 'solver',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'escrowToken',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
      {
        name: 'escrowAmount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'depositToken',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
      {
        name: 'depositAmount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'IntentSettled',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'id', internalType: 'bytes32', type: 'bytes32', indexed: true },
      {
        name: 'solver',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'tronTxId',
        internalType: 'bytes32',
        type: 'bytes32',
        indexed: false,
      },
      {
        name: 'tronBlockNumber',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'IntentSolved',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'id', internalType: 'bytes32', type: 'bytes32', indexed: true },
      {
        name: 'caller',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'prevSolver',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      { name: 'funded', internalType: 'bool', type: 'bool', indexed: false },
      {
        name: 'depositToCaller',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'depositToRefundBeneficiary',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'depositToPrevSolver',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'IntentUnclaimed',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'oldOwner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'newOwner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
    ],
    name: 'OwnershipTransferred',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'id', internalType: 'bytes32', type: 'bytes32', indexed: true },
      {
        name: 'feePpm',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'feeFlat',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'tronPaymentAmount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'ReceiverIntentFeeSnap',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'id', internalType: 'bytes32', type: 'bytes32', indexed: true },
      {
        name: 'forwarder',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'toTron',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'forwardSalt',
        internalType: 'bytes32',
        type: 'bytes32',
        indexed: false,
      },
      {
        name: 'token',
        internalType: 'address',
        type: 'address',
        indexed: false,
      },
      {
        name: 'amount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'ReceiverIntentParams',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'feePpm',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'feeFlat',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'RecommendedIntentFeeSet',
  },
  { type: 'error', inputs: [], name: 'AlreadyClaimed' },
  { type: 'error', inputs: [], name: 'AlreadyExists' },
  { type: 'error', inputs: [], name: 'AlreadyFunded' },
  { type: 'error', inputs: [], name: 'AlreadyInitialized' },
  { type: 'error', inputs: [], name: 'AlreadySolved' },
  { type: 'error', inputs: [], name: 'IncorrectPullAmount' },
  { type: 'error', inputs: [], name: 'InsufficientETH' },
  { type: 'error', inputs: [], name: 'IntentNotFound' },
  { type: 'error', inputs: [], name: 'InvalidDeadline' },
  { type: 'error', inputs: [], name: 'InvalidReceiverAmount' },
  { type: 'error', inputs: [], name: 'NewOwnerIsZeroAddress' },
  { type: 'error', inputs: [], name: 'NotATrc20Transfer' },
  { type: 'error', inputs: [], name: 'NotClaimed' },
  { type: 'error', inputs: [], name: 'NotExpiredYet' },
  { type: 'error', inputs: [], name: 'NotSolver' },
  { type: 'error', inputs: [], name: 'NothingToSettle' },
  { type: 'error', inputs: [], name: 'Reentrancy' },
  { type: 'error', inputs: [], name: 'TronInvalidCalldataLength' },
  { type: 'error', inputs: [], name: 'TronInvalidTrc20DataLength' },
  { type: 'error', inputs: [], name: 'Unauthorized' },
  { type: 'error', inputs: [], name: 'WrongTxProps' },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// UntronReceiver
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const untronReceiverAbi = [
  { type: 'constructor', inputs: [], stateMutability: 'nonpayable' },
  { type: 'receive', stateMutability: 'payable' },
  {
    type: 'function',
    inputs: [],
    name: 'OWNER',
    outputs: [{ name: '', internalType: 'address payable', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'token', internalType: 'address', type: 'address' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'pull',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  { type: 'error', inputs: [], name: 'NotOwner' },
] as const
