[project]
src = "src"
out = "out"
dot_env = ".env"
dependencies = ["pcaversaccio/snekmate"]

[networks.pyevm]
is_zksync = false

[networks.anvil]
url = "http://127.0.0.1:8545"
prompt_live = false
save_to_db = false
chain_id = 31337

[networks.mainnet]
url = "https://rpc.ankr.com/eth"
chain_id = 1

[networks.sepolia]
url = "https://ethereum-sepolia-rpc.publicnode.com"
chain_id = 11155111

[networks.base]
url = "https://mainnet.base.org"
chain_id = 8453

[networks.base-sepolia]
url = "https://sepolia.base.org"
chain_id = 84532

[networks.zksync-sepolia]
url = "https://sepolia.era.zksync.dev"
chain_id = 300
is_zksync = true
prompt_live = true

[networks.contracts]
UntronResolver = {  deployer_script = "deploy_resolver.py" }
UntronReceiverFactory = { deployer_script = "deploy_receiver_factory.py" }
UntronTransfers = {  deployer_script = "deploy_transfers.py" }

# You can view all configuration options at https://cyfrin.github.io/moccasin/all_moccasin_toml_parameters.html
