[project]
src = "src"
out = "out"
dot_env = ".env"
dependencies = ["pcaversaccio/snekmate"]

[networks.pyevm]
is_zksync = false

[networks.anvil]
url = "http://127.0.0.1:8545"
prompt_live = false
save_to_db = false
chain_id = 31337

[networks.mainnet]
url = "https://rpc.ankr.com/eth"
chain_id = 1

[networks.sepolia]
url = "https://ethereum-sepolia-rpc.publicnode.com"
chain_id = 11155111

[networks.base]
url = "https://mainnet.base.org"
chain_id = 8453

[networks.base-sepolia]
url = "https://sepolia.base.org"
chain_id = 84532

[networks.optimism]
url = "https://mainnet.optimism.io"
chain_id = 10

[networks.arbitrum]
url = "https://arb1.arbitrum.io/rpc"
chain_id = 42161

[networks.ink]
url = "https://rpc-gel.inkonchain.com"
chain_id = 57073

[networks.linea]
url = "https://rpc.linea.build"
chain_id = 59144

[networks.polygon]
url = "https://polygon-rpc.com"
chain_id = 137

[networks.soneium]
url = "https://rpc.soneium.org"
chain_id = 1868

[networks.unichain]
url = "https://unichain.drpc.org"
chain_id = 130

[networks.taiko]
url = "https://rpc.taiko.xyz"
chain_id = 167000

[networks.celo]
url = "https://forno.celo.org"
chain_id = 42220

[networks.lisk]
url = "https://rpc.api.lisk.com"
chain_id = 1135

[networks.mode]
url = "https://mainnet.mode.network"
chain_id = 34443

[networks.scroll]
url = "https://rpc.scroll.io"
chain_id = 534352

[networks.swellchain]
url = "https://rpc.ankr.com/swell"
chain_id = 1923

[networks.worldchain]
url = "https://worldchain-mainnet.g.alchemy.com/public"
chain_id = 480

[networks.zksync-sepolia]
url = "https://sepolia.era.zksync.dev"
chain_id = 300
is_zksync = true
prompt_live = true

[networks.contracts]
UntronResolver = {  deployer_script = "deploy_resolver.py" }
UntronReceiverFactory = { deployer_script = "deploy_receiver_factory.py" }
UntronTransfers = {  deployer_script = "deploy_transfers.py" }
UntronReceiver = {  deployer_script = "deploy_receiver.py"  }

# You can view all configuration options at https://cyfrin.github.io/moccasin/all_moccasin_toml_parameters.html
